kind: ServiceAccount
apiVersion: v1
metadata:
  name: loki-distributed
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/version: 2.5.0
secrets:
  - name: loki-distributed
  - name: loki-distributed-token
  - name: loki-distributed-dockercfg
imagePullSecrets:
  - name: loki-distributed-dockercfg
automountServiceAccountToken: true
